### ISSUE TITLE
Generate game installer

### ISSUE THREAD

**Issue by rodrigocam** [IJE-Valhalla/Litigium#17]
Generate a game installer for Linux/Windows platform, maybe it is necessary modify the image management.

**Comment by modihere** [comment]
Did you mean that an .exe file is to be generated?

**Comment by pablodiegoss** [comment]
i think so, or at least a .deb package to run the game in some other OS

**Comment by madduci** [comment]
Added a minimal CPack generation of DEB, RPM and Windows installers (NSIS/WIX) in #20

**Comment by rodrigocam** [comment]
Hi @madduci, to generate a NSIS installer I use cpack -G NSIS, is that correct? Because that installer is not working

**Comment by madduci** [comment]
you can just call cpack. The installer for windows is declared in line 2 of CPack.cmake file.

You **must** install WIX Toolset (if you want a MSI installer) and NSIS (for the EXE installer). You can obviously comment out (or remove) WIX from CPACK_GENERATOR and just launch 
`cpack` from command line or execute the project PACKAGE in Visual Studio, if you're using it.

The CPack.cmake file should be filled with some information, such as the PACKAGE_VERSION, PACKAGE_MAINTAINER and so on. I left them as variable but of course you're the project owner, so you should fill it with your details

**Comment by rodrigocam** [comment]
Ok, thank you @madduci !

**Comment by rodrigocam** [comment]
Issue resolved!
